name: Build and Test

on:
    push:
        branches:
            - master
        tags:
            - v*
    pull_request:
        branches:
            - master
            - prep-**
    workflow_dispatch:
        inputs:
          logLevel:
            default: warning
            description: "Log level"
            required: true
          tags: 
            description: "Test scenario tags"



jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build
              shell: bash
              env:
                WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
              run: ./ci/build.sh
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v1
              with:
                name: artifacts
                path: artifacts

    test-mac-required:
        needs: build
        name: Tests on Mac
        runs-on: macos-latest
        strategy:
            max-parallel: 1
            matrix:
                cloud: [ 'AWS' ]
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - uses: actions/setup-python@v1
              with:
                python-version: '3.7'
            - name: Download Build Artifacts
              uses: actions/download-artifact@v1
              with:
                name: artifacts
            - name: Install Homebrew Bash
              shell: bash
              run: brew install bash
            - name: Tests
              shell: bash
              env:
                PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
                CLOUD_PROVIDER: ${{ matrix.cloud }}
              run: /usr/local/bin/bash ./ci/test_mac.sh
